Make Pause, Stop Buttons on Print Screen update State
prusa3d/Prusa-Firmware-Buddy pull request #1053
Opened 2020-11-13 16:31 UTC by JeffersGlass

Addresses issue #1052  
https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1052

Previously, only the stopAction() on the printing screen updated the
state of the GUI (based on the state of the printer given by the
Marlin server. Now, both the Tune and Pause buttons will cause the
printer's state to update.

Signed-off-by: Jeff Glass <glass.jeffrey@gmail.com>

2020-11-18 16:07 UTC, RadekVana requested changes
Calling `change_print_state();` with `Screens::Access()->Open` or `Screens::Access()->Close` has not meaning, but could cause extra unwanted redraw just before screen is.
Please remove it.

Other changes are fine.

2020-11-18 16:07 UTC, RadekVana commented on src/gui/screen_printing.cpp
> +        change_print_state();
GUI supports only one screen at the time.
So `Screens::Access()->Open(GetScreenMenuTune);` will close (destroy) Print screen.
But `change_print_state()` could cause extra unwanted redraw just before it is closed.

Please remove it.

2020-11-18 16:07 UTC, RadekVana commented on src/gui/screen_printing.cpp
> +        change_print_state();
`change_print_state()` (with `Screens::Access()->Close();`) could cause extra unwanted redraw just before screen is closed.

Please remove it.

2020-11-20 10:39 UTC, RadekVana approved these changes

2020-11-20 10:41 UTC, DRracer commented
@JeffersGlass thank you for contributing to the Buddy Firmware. We made the slight changes for you, now the PR is ready to get merged.

2020-11-20 10:53 UTC, merged