tweak printing time and remaining time strings
prusa3d/Prusa-Firmware-Buddy pull request #1579
Opened 2021-09-08 15:43 UTC by pravdomil

Hello,
I want to tweak the **Printing time** and **Remaining Time** strings.
I think that more **Elapsed** and **Remaining** is more accurate.
It also fixes the title case typo.
What do you think?

![](https://www.fabbaloo.com/wp-content/uploads/2020/07/prusa-mini-panel-printing-1.jpeg)

2021-09-12 17:06 UTC, wavexx commented
I personally like this. Looks like the test failed for an unrelated change, fixed in #1586.

2021-09-14 13:48 UTC, MistrKernnunos requested changes
I quite like these changes too. 

The tests are not passing, beacuse ypu are changing files which are used to validate functionality of translation providers. I have attached comments to the files that should be reverted to their former state.

2021-09-14 13:48 UTC, MistrKernnunos commented on tests/unit/lang/translator/MOfilesTesting/en.txt
> +Elapsed
Please remove changes in the MOfilesTesting, these files are used for testing the translation provider and they dont reflect current state of translation in firmware

2021-09-14 13:48 UTC, MistrKernnunos commented on tests/unit/lang/translator/MOfilesTesting/en.txt
> +Remaining
The same as above

2021-09-14 13:48 UTC, MistrKernnunos commented on tests/unit/lang/translator/MOfilesTesting/keys.txt
> +Elapsed
The same as above

2021-09-14 13:48 UTC, MistrKernnunos commented on tests/unit/lang/translator/MOfilesTesting/keys.txt
> +Remaining
The same as above

2022-03-09 12:39 UTC, MistrKernnunos approved these changes
I am so sorry for taking so long to respond. 

Thanks for making this changes. You can mege the PR.

2022-03-14 11:25 UTC, merged