README: add virtualenv, tests
prusa3d/Prusa-Firmware-Buddy pull request #1581
Opened 2021-09-08 17:20 UTC by vorner

* Describe the possibility of separating the python packages in
  virtualenv.
* Describe how to run tests.

2021-09-09 11:03 UTC, DRracer commented on README.md
> +make tests
+ `ctest .` which actually runs the built tests

2021-09-09 11:04 UTC, DRracer requested changes
please add the `ctest .` to Build & run tests section, than it can be merged

2021-09-09 14:50 UTC, vorner commented
Thank you, I had the wrong impression that `make tests` would also run them 😇.

2021-09-10 09:02 UTC, DRracer approved these changes

2021-09-10 09:08 UTC, merged