Guide for WIFI/ESP connection for Original Prusa MINI
prusa3d/Prusa-Firmware-Buddy pull request #1751
Opened 2021-12-05 07:51 UTC by zoltan-l

Corrected and formatted files for ESP Guidelines

2021-12-05 16:13 UTC, foobarjimmy commented
I've compiled latest master branch,flashed ESP using ESP update and it connects to wireless network but freezes when return to menu.

2021-12-05 18:04 UTC, zoltan-l commented
Which version type did you compile ? Debug, release, .bbf?, bin?

2021-12-05 18:07 UTC, foobarjimmy commented
Release. Firmware was in .bbf

2021-12-05 21:07 UTC, zoltan-l commented
> Release. Firmware was in .bbf.It was compiled with “ —preset mini —generate-bbf” and all the other perimeters were not set.

I will check it and let you know, thanks for notification

2021-12-06 09:06 UTC, vorner commented
Could you describe few more details what happens? Does the whole printer freeze? Does it unfreeze after a while or is it stuck forever? Which menu, the main settings menu? Does it work after reboot?

2021-12-06 09:21 UTC, vorner requested changes
Again, bits of formatting. I'd provide some suggestions, but the comments here are also markdown and that makes it a bit hard 😇.

2021-12-06 09:21 UTC, vorner commented on doc/ESP/README.md
> +- In the prusa`_`printer_settings.ini file and under `[wifi]` tag edit the ssid and psk fields with the correct WiFi data
I was actually suggesting to put the whole file name as code snippet/monospace. Have you tried looking at how github renders it?

2021-12-06 09:21 UTC, vorner commented on doc/ESP/README.md
> +```key_mgmt=WPA```
The tripple ones are for bigger snippets, so it's:

Tripple backtickts
multiple lines of stuff
more lines
tripple backticks

That renders it as a single block of „code“

2021-12-06 09:21 UTC, vorner commented on doc/ESP/README.md
> +- Store the prusa`_`printer_settings.ini file in the root folder of the USB flash drive and plug in to the printer
Again…

2021-12-06 09:22 UTC, foobarjimmy commented
The whole printer was frozen and stuck forever after I return to the very top menu(with icons print,filament,settings,etc.).If I didn't go back to the top menu,everything(in the settings) worked just fine.And I had to toggle wifi on and off several times to get it connected but I thought that was something related to wireless network not the firmware.

2021-12-07 14:47 UTC, zoltan-l commented
I have followed the guide step ba step, used 4.3.3 +374 locel build by python. The printer did not, stop, so we really need a detailed step by step description.

2021-12-08 08:01 UTC, vorner approved these changes
I think we are good

2021-12-08 09:05 UTC, foobarjimmy commented
> I have followed the guide step ba step, used 4.3.3 +374 local. .bbf file build by python. The printer did not, stop!freeze, so we really need a detailed step by step description what you did.

It's stuck on the main menu with usb stick attached.Removing stick when this happen solves the issue.

I connected ESP and usb stick to the printer.Flashed the esp using menu items just like the guide.And loaded settings from usb stick but I didn't remove it after loading settings.Address was shown without problems in the lan settings.But printer froze after I exited to the main menu.It did unfreeze once I remove the usb stick.

2021-12-08 11:44 UTC, merged