Add "Enter DFU" option to Settings
prusa3d/Prusa-Firmware-Buddy pull request #1808
Opened 2022-01-08 18:35 UTC by dragomirecky

This adds a new item to Settings: „Enter DFU“. 

- When user clicks on it, the application jumps to the stm32 bootloader
- This item is available only in DEBUG build (as a dev item – a green one)

2022-01-10 08:18 UTC, vorner requested changes
The UB in there is probably not a practical problem, but it would be better to avoid anyway.

Btw, are we abusing the Real Time Clock to mark a flag that we want to reboot into DFU? :-O

2022-01-12 01:28 UTC, dragomirecky commented on src/common/sys.cpp
> +static const constexpr uint32_t DFU_REQUESTED_MAGIC_VALUE = 0xF1E2D3C5;
Made up by us. See `sys_dfu_request_and_reset` and `sys_dfu_requested`.

Should be possible to have there just a simple `0x01` flag, as I believe that the register is properly reset to 0 on RTC reset. This is just being a bit on the safer side (someone else using the register in future and me not being 100 % sure how this register behaves – eg. when the battery goes low).

2022-01-12 01:28 UTC, dragomirecky commented on src/common/sys.cpp
> +    } while (true);
✅

2022-01-13 09:15 UTC, vorner approved these changes

2022-01-13 09:36 UTC, merged