WUI: Proper locking during network setup
prusa3d/Prusa-Firmware-Buddy pull request #2030
Opened 2022-04-16 07:58 UTC by vorner

* Lock a mutex whenever we access shared data.
* This doesn't happen on hot-path / packet handling, only during
  "management" (setup, reading info for GUI, ...)
* It is probably a bit more conservative (locking more than necessary).
  It's easier to overlock than prove that it's not needed and as it's
  not on the hot path, better safe than sorry.

2022-04-19 04:52 UTC, DRracer commented on lib/WUI/wui.cpp
> +        xSemaphoreTake(mutex, portMAX_DELAY);
please consider a RAII pattern if possible

2022-04-19 04:53 UTC, DRracer requested changes
Please consider a RAII pattern approach if possible

2022-04-19 11:37 UTC, vorner commented
I'm pushing a version based on the std::lock APIs and the rtos mutex class I've already found lying around. I still need to test this version once I get a calm while, but that's not a reason to keep it to myself.

2022-04-20 10:36 UTC, DRracer approved these changes

2022-04-20 10:37 UTC, merged