Enable DNS for sntp and set default to pool.ntp.org
prusa3d/Prusa-Firmware-Buddy pull request #3730
Opened 2024-02-08 14:52 UTC by thess

This PR changes the default behavior of the SNTP client to use DNS name resolution for an NTP server target. The main advantage is load-balancing servers by using NTP server pools (eg: `pool.ntp.org`) which rotate addresses periodically via DNS. Another reason is the DNS query response from the pool is distributed by geography of requester as well.

I think this change and #3679 are complimentary - both are desired.

Ref: https://www.ntppool.org/

2024-03-09 23:58 UTC, MattBlissett commented
The NTP pool service doesn't allow people to use pool.ntp.org as a default, the vendor (Prusa) must ask for a custom name.

See https://www.ntppool.org/en/vendors.html#basic-guidelines

2024-04-04 13:13 UTC, thess commented
Yes, they do request you not use the default pool if you are a vendor. However, you can easily request and use a 'prusa' vendor pool (prusa.pool.ntp.org) and use that instead. It is better than the current hard-wired Czech CESNET NTP server and one will get   better geographic locality.

2024-06-26 12:53 UTC, danopernis requested changes
Good news everyone, NTP pool approved our request for vendor zone :partying_face: 

@thess can you please use `prusa3d.pool.ntp.org` ?

Also, this needs to be rebased onto current master. If you have difficulties with that, I can try rebasing in your fork, if I have the correct permissions.

2024-06-28 12:33 UTC, thess commented
@danopernis - glad to hear you got a Prusa3D NTP pool zone. I have made the requested change and have rebased the PR to the `master` branch with that change. PR #3679 is a super-set of this change with a lot more options for setting an NTP server. This PR is addressing the problem of having a fixed IP for NTP server time-setting functionality only.

2024-06-28 12:39 UTC, thess commented
Not sure what this CI failure is about -- nothing in my PR deals with this.
```
[387/1020] Generating qoi.data, ../gui/res/qoi_resources.gen
FAILED: src/resources/qoi.data src/gui/res/qoi_resources.gen /home/admin/workspace/rmware-Buddy_Multibranch_PR-3730/build/mini-en-pl_release_boot/src/resources/qoi.data /home/admin/workspace/rmware-Buddy_Multibranch_PR-3730/build/mini-en-pl_release_boot/src/gui/res/qoi_resources.gen 
cd /home/admin/workspace/rmware-Buddy_Multibranch_PR-3730/build/mini-en-pl_release_boot/src/resources && /home/admin/workspace/rmware-Buddy_Multibranch_PR-3730/.venv/bin/python3.10 /home/admin/workspace/rmware-Buddy_Multibranch_PR-3730/utils/qoi_packer.py /home/admin/workspace/rmware-Buddy_Multibranch_PR-3730/src/gui/res/png /home/admin/workspace/rmware-Buddy_Multibranch_PR-3730/build/mini-en-pl_release_boot/src/gui/res/qoi_resources.gen /home/admin/workspace/rmware-Buddy_Multibranch_PR-3730/build/mini-en-pl_release_boot/src/resources/qoi.data -input_filter=/home/admin/workspace/rmware-Buddy_Multibranch_PR-3730/src/gui/res/mini_used_imgs.txt
Traceback (most recent call last):
  File "/home/admin/workspace/rmware-Buddy_Multibranch_PR-3730/utils/qoi_packer.py", line 6, in <module>
    import qoi
  File "/home/admin/workspace/rmware-Buddy_Multibranch_PR-3730/.venv/lib/python3.10/site-packages/qoi/__init__.py", line 2, in <module>
    from qoi.qoi import QOIColorSpace, decode, encode, read, write
  File "src/qoi/qoi.pyx", line 1, in init qoi.qoi
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

2024-08-15 17:35 UTC, thess reviewed
Updated as requested

2024-08-16 06:50 UTC, danopernis approved these changes
@thess thanks, I am merging this. Sorry for the inconveniences due to rebasing.

2024-08-16 06:50 UTC, merged