gcode: m23 send serial msg on file select for octoprint / add missing M32 gcode cmd
prusa3d/Prusa-Firmware-Buddy pull request #3766
Opened 2024-02-18 18:49 UTC by bkerler

This addresses issue #3748 and adds a serial message that the file has been selected for octoprint.
Also implements missing m32 goce command.

2024-02-18 19:03 UTC, arekm commented
and https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2387

2024-02-26 09:40 UTC, danopernis requested changes
Looks OK, please just add the usual comment about  why we need SERIAL_ECHO there...

2024-02-29 19:27 UTC, bkerler commented
Done, added the comment :)

2024-03-05 11:06 UTC, danopernis approved these changes

2024-03-05 11:10 UTC, merged