WI_SWITCH_t : Ensure that variable "index" is private, preventing global use
prusa3d/Prusa-Firmware-Buddy pull request #4177
Opened 2024-09-01 21:28 UTC by bkerler

Reuse of the variable "index" within a WI_SWITCH_t derived class can lead to issues as index might be treated global although it should be treated as local variable, thus leading to functionality issues. By redefining index as private variable in WI_SWITCH_t and making usage of the defined GetIndex/SetIndex functions, similar issues can be prevented in the future.

This commit is based on the issue #3155 and needs the additional PR #4176 in order to make sure it compiles correctly.

2024-09-02 07:31 UTC, CZDanol requested changes
See https://github.com/prusa3d/Prusa-Firmware-Buddy/pull/4176 for first commit issues. The correct solution would be to do:
```SetIndex(netdev_get_ip_obtained_type(this->device_id()));``` 
instead of
```index = netdev_get_ip_obtained_type(this->device_id());```

2024-09-02 08:06 UTC, bkerler commented
Updated, looks like it does build fine now :)

2025-02-03 08:34 UTC, CZDanol approved these changes

2025-02-03 08:59 UTC, CZDanol commented
Internal ticket: BFW-6709

2025-02-10 09:51 UTC, michalrudolf commented
I have removed the `GetIndex() -> get_index()` change from MMU code (unrelated change) and force-pushed the commit to your branch. Now we can merge it.

2025-02-10 09:53 UTC, michalrudolf approved these changes

2025-02-10 10:12 UTC, merged