Closes #3870 - improve nozzle diameter footer item
prusa3d/Prusa-Firmware-Buddy pull request #4263
Opened 2024-10-19 14:53 UTC by jakubtkadlecek

I have found 

https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3870

quite distracting during nozzle changes, due to footer item number not corresponding to actual inputted number. Touch version of nozzle diameter input autocorrection feature as well as nozzle diameter warning check in combination with truncated number can in case of mismatch add to confusion.

I have dropped original 'g' formatting in favour of fixed decimal places and manual zero and decimal point removal, since I don't think this is easily achievable otherwise. Appending of dimensions looks a bit iffy, but the use-case seemed like overkill for StringBuilder. Usage of buffer fill could be avoided by testing for 'm' character in the cleaning loop, but results was IMO less understandable. 

0.25
<img width="483" alt="nozzle_0_25" src="https://github.com/user-attachments/assets/aeda03aa-c1bb-4873-a17e-67fec21e1ecc">

0.40
<img width="482" alt="nozzle_0_4" src="https://github.com/user-attachments/assets/76fe8753-2d96-4204-b215-90e74c8c0403">

1.00
<img width="482" alt="nozzle_1" src="https://github.com/user-attachments/assets/53ab1172-6da4-4145-8d16-f4fb8dcd968a">

1.05
<img width="481" alt="nozzle_1_05" src="https://github.com/user-attachments/assets/6b650e34-d13c-4503-b4a3-ca052423cc49">

1.10
<img width="481" alt="nozze_1_1" src="https://github.com/user-attachments/assets/890fd681-e8f9-4a59-a38d-2ca8229dd774">

2024-10-19 17:43 UTC, CZDanol requested changes
Please have a look at StringBuilder::append_float. It should do what you want to and using it would make the code more readable.

2024-10-20 16:44 UTC, jakubtkadlecek commented
Indeed it does. Thanks for taking the time @CZDanol!

2024-10-20 20:30 UTC, CZDanol approved these changes

2024-10-20 20:31 UTC, CZDanol commented on src/gui/footer/footer_items_nozzle_bed.cpp
> +    return string_view_utf8::MakeRAM((const uint8_t *)(buff.data()));
Nitpick: that cast to uint8_t is no longer needed :)

2024-10-20 20:31 UTC, CZDanol commented on src/gui/footer/footer_items_nozzle_bed.cpp
>  #pragma GCC diagnostic ignored "-Wformat-truncation"
Nitpick: This GCC formatting is no longer needed as well

2024-10-20 20:35 UTC, CZDanol commented
Nice, thanks :) I will try to not forget merge it tomorrow. Feel free to remind me.

2024-10-21 09:28 UTC, CZDanol commented
Internal ticket: BFW-6223

2024-10-22 07:25 UTC, jakubtkadlecek commented
Hey @CZDanol! I have addressed nitpicks in the latest commit.

2024-10-22 08:00 UTC, CZDanol commented
Thanks, good job :) I'm waiting for the second approval within the team - then I'll to the merge.

2024-10-22 08:00 UTC, CZDanol approved these changes

2024-10-23 09:56 UTC, merged