Add unit test for extremely long file names
prusa3d/Prusa-Firmware-Buddy pull request #620
Opened 2020-06-24 14:37 UTC by DRracer

Expected to fail for now, such files are not accepted into the file browser, thus the user cannot print them. To be solved in the future.

BFW-1041

2020-09-25 14:53 UTC, marekmosna-prusa3d requested changes

2020-09-25 14:53 UTC, marekmosna-prusa3d commented on tests/unit/gui/lazyfilelist/fatfs.cpp
> +    if (strlen(lfn) >= 13) {
those 13 represent FF_SFN_BUF?

2020-09-29 10:46 UTC, DRracer commented on tests/unit/gui/lazyfilelist/fatfs.cpp
> +    if (strlen(lfn) >= 13) {
yes, improved in the next commit

2020-09-29 10:58 UTC, marekmosna-prusa3d approved these changes

2020-09-29 11:31 UTC, merged