Text roll cpp
prusa3d/Prusa-Firmware-Buddy pull request #971
Opened 2020-10-16 00:46 UTC by RadekVana

2020-10-19 07:19 UTC, DRracer commented on src/guiapi/include/window_event.hpp
> +        return N_("button down");
do we really want to translate these "debug" texts?

2020-10-19 09:46 UTC, DRracer requested changes
Please remove the N_() macro from the debug texts

2020-10-19 12:27 UTC, espr14 requested changes

2020-10-20 08:11 UTC, DRracer approved these changes

2020-10-20 08:50 UTC, DRracer approved these changes

2020-10-20 08:55 UTC, espr14 approved these changes

2020-10-20 08:58 UTC, merged